services:
  api:
    build:
      context: .
    container_name: sis_paguyuban_api
    env_file:
      - .env
    environment:
      - CI_ENV=production
    ports:
      - "8083:80"
    networks:
      - shared_apps
    restart: unless-stopped

networks:
  shared_apps:
    external: true
