version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sis_harmoni_app
    ports:
      - "8083:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - CI_ENV=testing

  db:
    image: mariadb:10.6
    container_name: sis_harmoni_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sis_harmoni
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sis-paguyuban-db-02022026-1.0.4.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
