version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sis_harmoni_app
    ports:
      - "8083:80"
    environment:
      - CI_ENV=production
    env_file:
      - .env
    networks:
      - shared_apps
    restart: unless-stopped

networks:
  shared_apps:
    external: true
