version: '3.8'

services:
  github-runner:
    image: myoung34/github-runner:latest
    restart: always
    environment:
      REPO_URL: ${REPO_URL}
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      RUNNER_NAME: ${RUNNER_NAME:-sis-harmoni-runner}
      RUNNER_LABELS: ${RUNNER_LABELS:-self-hosted,docker}
      RUNNER_WORKDIR: /tmp/runner/work
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
